name: 'Bikeclub Events'
description: 'Provides Event and Location content types.'
type: 'Content type'
recipes:
  - bikeclub_content_type_base
  - bikeclub_registration_field_storage
  - bikeclub_banner
  - bikeclub_locations
install:
  - link
  # Contrib.
  - calendar_view
  - datetimehideseconds
  - smart_date
  - webform
  - webform_node
  - webform_options_limit
  - webform_templates
  - webform_ui
  - webform_views
config:
  strict: false
  import:
    smart_date: '*'
    webform: '*'
  actions:
    webform.settings:
      simpleConfigUpdate:
        default_submission_views:
          embed_administer:
            title: 'Administer submissions'
            view: 'webform_submissions_custom:embed_administer'
            global_routes:
              - entity.webform_submission.collection
            webform_routes: {  }
            node_routes: {  }
        file_public: true
    user.role.events_coordinator:
      createIfNotExists:
        label: 'Events coordinator'
      # 'Webform' refers to the forms, not webform nodes.
      grantPermissions:
        - 'access own webform configuration'
        - 'access webform help'
        - 'access webform overview'
        - 'configure editable event node layout overrides'
        - 'create event'
        - 'create webform content'
        - 'delete own webform'
        - 'delete any event content'
        - 'edit own webform'
        - 'edit any event content'
        - 'use text format basic_html'
        - 'use text format summary_fields'
    user.role.site_admin:
      createIfNotExists:
        label: 'Site administrator'
      grantPermissions:
        - 'access own webform configuration'
        - 'access webform help'
        - 'access webform overview'
        - 'configure editable event node layout overrides'
        - 'create event'
        - 'create webform content'
        - 'delete own webform'
        - 'delete any event content'
        - 'edit own webform'
        - 'edit any event content'
        - 'use text format basic_html'
        - 'use text format summary_fields'
    user.role.authenticated:
      grantPermissions:
        - 'delete own webform submission'
        - 'view webform submissions own node'
    pathauto.pattern.content:
      simpleConfigUpdate:
        bundles:
          event: event
    webform.settings:
      ui:
        video_display: hidden
      file:
        file_public: true

