name: 'Bikeclub Events'
description: 'Provides Event content type.'
type: 'Content type'
recipes:
  - bikeclub_content_type_base
  - bikeclub_field_storage_registration
  - bikeclub_banner
  - bikeclub_locations
install:
  - link
  - menu_ui  
  # Contrib.
  - conditional_fields
  - datetimehideseconds
  - smart_date
  - webform
  - webform_civicrm
config:
  actions:
    user.role.site_admin:
      createIfNotExists:
        - label: 'Site administrator'
      grantPermissions:
        - 'create event content'
        - 'create location content'
        - 'delete any event content'
        - 'delete any location content'
        - 'edit any event content'
        - 'edit any location content'
        - 'configure editable event node layout overrides'
        - 'use text format basic_html'
        - 'use text format summary_fields'
    user.role.events_coordinator:
      createIfNotExists:
        - label: 'Events coordinator'
      grantPermissions:
        - 'create event content'
        - 'create location content'
        - 'delete own event content'
        - 'delete own location content'
        - 'edit own event content'
        - 'edit own location content'
        - 'configure editable event node layout overrides'
        - 'use text format basic_html'
        - 'use text format summary_fields'
